---
- name: Ensure data directory
  become: yes
  ansible.builtin.file:
    path: '{{ data_dir }}'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Ensure data sub directories
  become: yes
  ansible.builtin.file:
    path: '{{ item.value.path }}'
    state: directory
    owner: '{{ item.value.owner | default(ansible_user) }}'
    group: '{{ item.value.group | default(ansible_user) }}'
    mode: "{{ item.value.mode | default('0750') }}"
  loop: '{{ data_dirs | dict2items }}'

- name: Check if default environment variables file exists
  stat:
    path: '{{ env_variables_file }}'
  register: env_variables_file_stat
  delegate_to: localhost

- name: Include default environment variables
  ansible.builtin.include_vars:
    file: '{{ env_variables_file }}'
    name: env_variables
    hash_behaviour: merge
  when: env_variables_file_stat.stat.exists

- name: Check if host specific environment variables file exists
  stat:
    path: '{{ env_variables_host_file }}'
  register: env_variables_host_file_stat
  delegate_to: localhost

- name: Include host specific environment variables
  ansible.builtin.include_vars:
    file: '{{ env_variables_host_file }}'
    name: env_variables
    hash_behaviour: merge
  when: env_variables_host_file_stat.stat.exists

- name: Check if default secret environment variables file exists
  stat:
    path: '{{ secret_env_variables_file }}'
  register: secret_env_variables_file_stat
  delegate_to: localhost

- name: Include default secret environment variables
  ansible.builtin.include_vars:
    file: '{{ secret_env_variables_file }}'
    name: secret_env_variables
    hash_behaviour: merge
  when: secret_env_variables_file_stat.stat.exists

- name: Check if host specific secret environment variables file exists
  stat:
    path: '{{ secret_env_variables_host_file }}'
  register: secret_env_variables_host_file_stat
  delegate_to: localhost

- name: Include host specific secret environment variables
  ansible.builtin.include_vars:
    file: '{{ secret_env_variables_host_file }}'
    name: secret_env_variables
    hash_behaviour: merge
  when: secret_env_variables_host_file_stat.stat.exists

- name: Set local repo path
  ansible.builtin.set_fact:
    local_repo_path: "{{ playbook_dir }}/repo"

- name: Ensure repo directory
  ansible.builtin.file:
    state: directory
    path: "{{ local_repo_path }}"
  delegate_to: localhost

- name: Checkout repo locally
  ansible.builtin.git:
    repo: '{{ docker_git_repo_url }}'
    dest: '{{ local_repo_path }}'
    version: '{{ docker_git_revision }}'
    force: yes
  delegate_to: localhost

- name: Set release directory paths
  ansible.builtin.set_fact:
    release_path: "{{ release_path }}"
    release_secrets_env_example_file_path: "{{ [release_path, 'secrets.env.example'] | path_join }}"
    release_secrets_env_file_path: "{{ [release_path, 'secrets.env'] | path_join }}"
    release_env_file_path: "{{ [release_path, '.env'] | path_join }}"
  vars:
    release_id: "{{ ansible_date_time.iso8601_basic_short }}-{{ git_revision }}"
    release_path: "{{ [releases_path, release_id] | path_join }}"

- name: Copy docker directory to release directory
  ansible.builtin.copy:
    src: "{{ local_repo_docker_path }}/"
    dest: "{{ release_path }}/"
    mode: preserve

- name: Check if secrets.env.example exists
  ansible.builtin.stat:
    path: '{{ release_secrets_env_example_file_path }}'
  register: release_secrets_env_example_file_stat

- name: Copy secrets.env.example to secrets.env
  ansible.builtin.copy:
    remote_src: true
    src: '{{ release_secrets_env_example_file_path }}'
    dest: '{{ release_secrets_env_file_path }}'
  when: release_secrets_env_example_file_stat.stat.exists

- name: Set variables in secrets.env
  ansible.builtin.replace:
    path: '{{ release_secrets_env_file_path }}'
    regexp: '^{{ item.key }}=.*'
    replace: '{{ item.key}}={{ item.value }}'
  loop: '{{ secret_env_variables | dict2items }}'
  when: release_secrets_env_example_file_stat.stat.exists

- name: Check if .env file exists
  ansible.builtin.stat:
    path: '{{ release_env_file_path }}'
  register: release_env_file_stat

- name: Set variables in .env
  ansible.builtin.replace:
    path: '{{ release_env_file_path }}'
    regexp: '^{{ item.key }}=.*'
    replace: '{{ item.key}}={{ item.value }}'
  loop: '{{ env_variables | dict2items }}'
  when: release_env_file_stat.stat.exists

- name: Run docker scripts
  ansible.builtin.command: "./{{ item }}"
  args:
    chdir: "{{ release_path }}"
  loop: "{{ docker_scripts }}"

- name: Switch current relase symlink
  ansible.builtin.file:
    src: "{{ release_path }}"
    dest: "{{ current_release_path }}"
    state: link
    force: true

- block: # TODO: Docker compose down in old release directory if exists?
    - name: Ensure containers are pulled
      ansible.builtin.shell:
        chdir: '{{ current_release_path }}'
        cmd: '{{ docker_command }} pull'

    - name: Ensure containers are up
      ansible.builtin.shell:
        chdir: '{{ current_release_path }}'
        cmd: '{{ docker_command }} up -d'
  tags: restart

- name: Find existing releases
  ansible.builtin.find:
    path: '{{ releases_path }}'
    file_type: directory
    recurse: false
  register: releases

- name: Sort releases
  ansible.builtin.set_fact:
    sorted_releases: "{{ releases.files | sort(attribute='path', reverse=true) }}"

- name: Remove releases if more than release count
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ sorted_releases[release_count:] }}"

- name: Ensure apache configuration
  become: yes
  ansible.builtin.template:
    owner: root
    src: '{{ item }}'
    dest: "/opt/gub-apache2/sites/{{ item | basename | regex_replace('\\.conf\\.j2$', replace) }}"
  vars:
    replace: '{{ apache_site_conf_suffix }}'
  with_fileglob: '{{ playbook_dir }}/templates/sites/*.conf.j2'
  notify: reload apache

- name: Check if shared apache configuration exists
  ansible.builtin.stat:
    path: '{{ playbook_dir }}/templates/sites/conf'
  register: shared_apache_conf_stat
  delegate_to: localhost

- name: Ensure shared apache configuration
  become: yes
  ansible.builtin.template:
    owner: root
    src: '{{ item }}'
    dest: "/opt/gub-apache2/conf-shared/{{ item | basename | regex_replace('\\.j2$','') }}"

  with_fileglob: '{{ playbook_dir }}/templates/sites/conf/*.conf.j2'
  notify: reload apache
  when: shared_apache_conf_stat.stat.exists

- name: Check if cron configuration exists
  ansible.builtin.stat:
    path: '{{ playbook_dir }}/templates/cron.d'
  register: cron_d

- name: Ensure cron configuration
  become: yes
  ansible.builtin.template:
    owner: root
    src: '{{ item }}'
    dest: "/etc/cron.d/{{ item | basename | regex_replace('\\.j2$','') }}"
  with_fileglob: '{{ playbook_dir }}/templates/cron.d/*.j2'
  when: cron_d.stat.exists
